version: '3.8'

services:
  pilot-docs:
    image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    restart: unless-stopped
    container_name: pilot-docs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pilot-docs.rule=Host(`pilot.quantflow.studio`)"
      - "traefik.http.routers.pilot-docs.entrypoints=websecure"
      - "traefik.http.routers.pilot-docs.tls=true"
      - "traefik.docker.network=balancer"
    expose:
      - 3000
    volumes:
      - /data/quantflow/pilot_cache:/app/.next/cache
    networks:
      - balancer

networks:
  balancer:
    external: true
    name: balancer
